name: "Post to Bluesky"

on:
  schedule:
    - cron: "45 11,23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Send post
        run: python alltherecipesbot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}